### ISSUE TITLE
SemanticDB Generation (gives find references)

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#105]
from TODO list

**Comment by kpodsiad** [comment]
AFAIK, this issue cannot be resolved without changes in scala_rules, see https://github.com/bazelbuild/rules_scala/issues/952

**Comment by abrams27** [comment]
one more `scala_rules` change!

**Comment by abrams27** [comment]
moved to: https://youtrack.jetbrains.com/issue/BAZEL-38
