### ISSUE TITLE
Errors reported in the UI are trimmed

### ISSUE THREAD

**Issue by lukaszwawrzyk** [JetBrains/bazel-bsp#112]
Hi!
I see couple of problems with errors reporting. I have a compile error. I used symbol that doesn't exist 3 times. Note that by default last node is highlighted. It contains just first lone of the error, that the java compiler failed, but not why, which is not very useful.

Also note the empty error node, It shouldn't be there.

![image](https://user-images.githubusercontent.com/10235198/145970513-aeef1e61-fc37-48a4-a88f-e8bb34782312.png)

I need to go to the root to see the actual errors and scroll a bit.

![image](https://user-images.githubusercontent.com/10235198/145970620-bdf8f008-4fa6-4124-b9b8-5358ecf279f4.png)

Lastly, note that lines from bazel output are trimmed, thus the cursor pointing to the error (^) is always at the beginning on the line instead of at the symbol. Compare to console output:

![image](https://user-images.githubusercontent.com/10235198/145972017-bc7eef20-c215-4752-b431-96008b237396.png)

edit:
I found one more issue: after failed build, IntelliJ automatically navigates to the error, but it goes to BUILD file instead of java file with error.

**Comment by abrams27** [comment]
BUILD file bug is know: https://github.com/JetBrains/bazel-bsp/issues/67, https://github.com/JetBrains/bazel-bsp/issues/111
