### ISSUE TITLE
Multiple targets in one file create 1 module rather than module per target

### ISSUE THREAD

**Issue by lukaszwawrzyk** [JetBrains/bazel-bsp#114]
Take a look at this example project:
![image](https://user-images.githubusercontent.com/10235198/145983741-a7e726f5-3d12-4f91-bd5d-2bde24e7bdd3.png)
In such case I think 2 modules should be created instead.  The targets may have completely different set of dependencies which cannot be expressed with current approach. In this specific case it worked fine as the only dependency that is exclusive to test target was marked as test dependency, but in general case, if both of these were regular targets, it wouldn't work. Also note that package prefix is set incorrectly.

**Comment by abrams27** [comment]
I believe that it is more like a client bug

**Comment by abrams27** [comment]
like I said, it seems to be a client issue - in general it is a bit tricky to represent such case using current IntelliJ project structure.
