### ISSUE TITLE
Imported targets are also visible as libraries

### ISSUE THREAD

**Issue by lukaszwawrzyk** [JetBrains/bazel-bsp#117]
I imported project with 3 targets: 
```
//jvm_hello/src/main/java/com/hello:java_hello
//jvm_hello/src/test/java/com/hello/tests:test
//thrift_hello:thrift_hello_scrooge
```

Note that in the libraries are 2 libraries for each jvm target, i.e. java_hello, java_hello-src, test and test-src. src libraries point to file that does not exist. Each module for jvm target depends on its libraries, i.e. java_hello module depends on java_hello and java_hello-src libraries. The libraries contain compiled code of their targets.
Why are these created? It effectively triples the number of entites in the project.

Also another thing. Why are 3rd party libraries doubled with -stamped suffix? It also seems to double number of libraries and IntelliJ is known to slow down or freeze with too many order entries.

![image](https://user-images.githubusercontent.com/10235198/146022316-c76bed4b-740e-4a24-af3e-c41174a8c121.png)

**Comment by abrams27** [comment]
I believe that it is also a client bug, if yes - https://github.com/JetBrains/intellij-scala/tree/idea213.x/bsp. New client'll address such issues as well

**Comment by lukaszwawrzyk** [comment]
seems to be fixed by new sync mechanism
