### ISSUE TITLE
Support for multiple projects in one repo

### ISSUE THREAD

**Issue by lukaszwawrzyk** [JetBrains/bazel-bsp#122]
I am looking for a solution to have many projects open in parallel on one bazel workspace/vcs root. The goal is to have a directory for projects, it can be inside or outside repo. For example fastpass does REPO/../bsp-projets/PROJECT or our custom integration with bazel and google's plugin does REPO/bazel-imports/PROJECT.
The PROJECT dir should contain the .bsp, .bazelbsp, .idea directories and anything else that is necessary like projectview file or symlinks. IntelliJ would open project in this dir and should still show the whole repo once the bsp project sync completes.
Currently this scenario seems impossible, as I see no path to workspace anywhere, It seems like it is assumed to be .bsp/.. dir. Also I can only place projectview in the root of repository.

**Comment by abrams27** [comment]
i'll try to address it,

> Also I can only place projectview in the root of repository.

i'll try to make it more configurable, even from the client side, but I'm not sure how to do it properly yet
