### ISSUE TITLE
Bazel BSP for Java

### ISSUE THREAD

**Issue by brown** [JetBrains/bazel-bsp#138]
I would like to use Bazel BSP with a Java project.  The documentation says the server works with Java, but there's no description of how to use the server with Java.  The setup process is only documented for Scala.

I'd really appreciate if instructions were added for Java.

**Comment by abrams27** [comment]
installation of the server is [the same](https://github.com/JetBrains/bazel-bsp#installation):
```
cs launch org.jetbrains.bsp:bazel-bsp:1.0.1 -M org.jetbrains.bsp.bazel.install.Install
```

I'll update the documentation
