### ISSUE TITLE
java 17

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#173]
maybe it would be nice to use java 17 in the project + add more tests for java versions as well

**Comment by lukaszwawrzyk** [comment]
I'd really love to have records from java 17 for example. One thing to consider is how we are going to run it on user machines. Java 11 is more popular and default on user machines.
I think to make this transition we should also enhance launcher to be able to download and install java 17 and use it to launch the server. Likely this can be handled with coursier somehow.

**Comment by abrams27** [comment]
we can run server with `bazel run` with `--java_runtime_version=remotejdk_17` flag - then the server will work even on machines without jam

**Comment by lukaszwawrzyk** [comment]
But to use bazel run you need to have sources and build them on client machine, right?

**Comment by abrams27** [comment]
or maybe just move to Kotlin?

**Comment by abrams27** [comment]
kooootlin
