### ISSUE TITLE
cpp plugin implementation

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#186]
the cpp language plugin is not implemented yet in new (awesome) sync mechanism https://github.com/JetBrains/bazel-bsp/pull/147

(cpp e2e tests are temporary disabled)

**Comment by agluszak** [comment]
I'll take it, cc @lukaszwawrzyk

**Comment by abrams27** [comment]
moved: https://youtrack.jetbrains.com/issue/BAZEL-25
