### ISSUE TITLE
Further reorganisation and breaking down of BazelBspServerBuildManager and BuildServerService

### ISSUE THREAD

**Issue by gerardd33** [JetBrains/bazel-bsp#26]
Suggested by @andrefmrocha
https://github.com/JetBrains/bazel-bsp/pull/24#discussion_r549167298
https://github.com/JetBrains/bazel-bsp/pull/24#discussion_r549165815
https://github.com/JetBrains/bazel-bsp/pull/24#discussion_r549483018

**Comment by Abrams27** [comment]
have we fixed it somehow?
