### ISSUE TITLE
Native Kotlin Support

### ISSUE THREAD

**Issue by andrefmrocha** [JetBrains/bazel-bsp#3]
In order to proper support all of the features of [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/), there is a need for native Kotlin support over the BSP. After an extension of the protocol for kotlin has been built, it should be supported, especially in order to support KotlinJS modules.

**Comment by Abrams27** [comment]
@agluszak was doing something with kotlin. Is there anything to add?

**Comment by abrams27** [comment]
moved to YouTrack: https://youtrack.jetbrains.com/issue/BAZEL-7
