### ISSUE TITLE
Notify the client when server initialization fails

### ISSUE THREAD

**Issue by agluszak** [JetBrains/bazel-bsp#31]
In one of the previous PRs (#18) I moved the code responsible for fetching bazel data (workspace root etc.) to the constructor of BspServer. It simplified the logic, but now I realized it also has an unfortunate effect: when Bazel fails to fetch this data with `bazel info`, the whole server crashed *before* it is possible to notify the client. Such crash can happen for example because of a typo in the `WORKSPACE` file, so it would be a totally reasonable thing to do to forward the failure massage to the client. 

TODO:
- [ ] change the code so that bazel data is fetched during handling of the initial client request
- [ ] if it fails, relay the message generated by bazel (i.e. the client should receive the full output of the `/usr/bin/bazel info` call)
- [ ] test this behavior of course ;_;

**Comment by Abrams27** [comment]
have we fixed it somehow?

**Comment by abrams27** [comment]
it was fixed by new sync mechanism
