### ISSUE TITLE
Failed to import dependencies from rules_jvm_external

### ISSUE THREAD

**Issue by andrefmrocha** [JetBrains/bazel-bsp#54]
Steps to reproduce:
- Open the `rules_jvm_external` repository (https://github.com/bazelbuild/rules_jvm_external/tree/4.0) with bazel bsp
- Open a files with maven dependencies, such as `MavenPublisher.java`

Its external dependencies are not found

**Comment by abrams27** [comment]
moved: https://youtrack.jetbrains.com/issue/BAZEL-27
