### ISSUE TITLE
Fake Bazel specific files module

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#59]
Currently bazel specific files (`WORKSPACE`, `.bazelrc`) are outside of project - what is annoying when editing.

The solution could be adding "fake" module/target for those files (excluding ones from `.gitignore`)

**Comment by Abrams27** [comment]
another approach could be updating protocol

**Comment by jastice** [comment]
We should support that "fake"/virtual target either way to support bazel-specific metadata in these files (and also add this feature to the protocol), but the simplest aproach would be to make such a virtual target on the client side for the project root.

**Comment by lukaszwawrzyk** [comment]
I think this is done already.
if //... is imported, the workspace root is returned as a synthetic target. For cases like `//target_a/...` users do not want to look at the root of repo usually.
