### ISSUE TITLE
Use an aspect output group to obtain dependencies

### ISSUE THREAD

**Issue by andrefmrocha** [JetBrains/bazel-bsp#6]
Currently the `buildTarget/dependencySources` request parses the output of an aspect. Even though this is stable, there would be some value in substituting this with an Output Group, like [this example](https://docs.bazel.build/versions/master/skylark/rules.html#requesting-output-files)

**Comment by andrefmrocha** [comment]
More examples are beginning to emerge on how aspects are a better way of obtaining most information about bazel:
- it's already being used to get jdk information in #43 
- it will have to be used to obtain information from c++ targets as well.

I'm thinking that after wrapping up these features, it is probably a good idea to finally refactor aspects in order to have a better way of obtaining these information that isn't parsing the stderr. Would love to hear your opinion on this @agluszak @Abrams27 @gerardd33 @magda-aug

**Comment by abrams27** [comment]
https://github.com/JetBrains/bazel-bsp/pull/147
