### ISSUE TITLE
Intellij tests running fix

### ISSUE THREAD

**Issue by Abrams27** [JetBrains/bazel-bsp#63]
Now, green triangles in Intellij don't run tests properly via BSP - probably client-sided problem.

**Comment by jastice** [comment]
Yes, this is client side issue. IntelliJ has some problems supporting multiple test runners for those triangles, so we give preference to the default runners and disabled BSP support for them. Currently the only way to run tests over BSP is to manually create a run config.

**Comment by Abrams27** [comment]
not strictly Bazel bsp problem
