### ISSUE TITLE
Server not responding to initialize request.

### ISSUE THREAD

**Issue by ckipp01** [JetBrains/bazel-bsp#64]
Hello! Thanks for the great work you've put into this so far. I've been itching to try and see how this would work with [Metals](https://scalameta.org/metals/), so I dug in a bit today but hit a couple snags that I was hoping someone might have some more insight into.

Firstly I tried the readme instructions with `coursier launch -r sonatype:snapshots org.jetbrains.bsp:bazel-bsp:0.1.0 -M org.jetbrains.bsp.bazel.Install`, however there seems to have been a lot of work since `0.1.0` was release. Plus, when trying that version I get a lot of internal errors like:

(Note these are traces from the Metals perspective)
```
[Trace - 11:48:47 AM] Received notification 'build/logMessage'
Params: {
  "type": 1,
  "message": "Command aborted with reason LOADING_FAILURE: error loading package \u0027bazel-bazel_scala_example/external/io_bazel_rules_scala/scala_proto\u0027: Label \u0027//scala_proto:scala_proto_toolchain.bzl\u0027 is invalid because \u0027scala_proto\u0027 is not a package; perhaps you meant to put the colon here: \u0027//:scala_proto/scala_proto_toolchain.bzl\u0027?"
}
...

[Trace - 11:48:48 AM] Received notification 'build/logMessage'
Params: {
  "type": 4,
  "message": "Loading: 0 packages loaded\nERROR: Error while parsing \u0027()\u0027: syntax error at \u0027)\u0027\nLoading: 0 packages loaded"
}


[Trace - 11:48:48 AM] Received notification 'build/logMessage'
Params: {
  "type": 1,
  "message": "Command aborted with reason INTERNAL: "
...
```

I sort of assumed that these were coming from the bsp side mainly due to me not defining anything with proto. Anyways, this led me to then try out the latest dev branch using `buildAndRunLocally.sh` and pointing it to a very minimal [example project](https://github.com/ckipp01/metals_bazel_tester).

The `.bsp/bazelbsp.json` file does appear to be created fine:

```
{
  "name": "bazelbsp",
  "argv": [
    "/usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java",
    "-classpath",
    "...super long classpath",
    "org.jetbrains.bsp.bazel.server.ServerInitializer",
    "/usr/local/bin/bazel"
  ],
  "version": "0.0.0",
  "bspVersion": "2.0.0",
  "languages": [
    "scala",
    "java",
    "kotlin"
  ]
}
```

When Metals starts up and attempts to initiate the BSP process the request to initialize is sent in:

```
[Trace - 11:57:34 AM] Sending request 'build/initialize - (1)'
Params: {
  "rootUri": "file:///Users/ckipp/Documents/scala-workspace/metals_bazel_tester/",
  "displayName": "Metals",
  "version": "0.10.5-SNAPSHOT",
  "bspVersion": "2.0.0-M13",
  "capabilities": {
    "languageIds": [
      "scala"
    ]
  },
  "data": {
    "semanticdbVersion": "4.4.21",
    "supportedScalaVersions": [
      "2.13.6",
      "2.12.14",
      "2.12.13",
      "2.12.12",
      "2.12.11",
      "2.12.10",
      "2.13.3",
      "2.13.4",
      "2.13.5",
      "2.11.12",
      "2.12.8",
      "2.12.9",
      "2.13.0",
      "2.13.1",
      "2.13.2"
    ]
  }
}
```
But it seems to never succeed, no response is sent back, and times out. Looking at the `.bazelbsp/bazelbsp.all.log` file the only thing I continually see is:

```
2021-06-16 11:57:54.918 [main] INFO    org.jetbrains.bsp.bazel.server.bazel.BazelRunner - Waiting for bazel - command: info, flags: [], arguments: [bazel-bin]
2021-06-16 11:57:54.918 [main] INFO    org.jetbrains.bsp.bazel.server.bazel.BazelRunner - Running: [/usr/local/bin/bazel, info, bazel-bin]
2021-06-16 11:57:55.050 [main] INFO    org.jetbrains.bsp.bazel.server.bazel.BazelRunner - Waiting for bazel - command: info, flags: [], arguments: [release]
2021-06-16 11:57:55.051 [main] INFO    org.jetbrains.bsp.bazel.server.bazel.BazelRunner - Running: [/usr/local/bin/bazel, info, release]
```

Any idea what may be happening here and why the server is never able to initialize? My example project is [here](https://github.com/ckipp01/metals_bazel_tester) and I'm not super familiar with Bazel, so I'm not ruling out that I did something wrong. However, with the `0.1.0` it does initialize with that build, so I'd assume it should with the latest `dev` as well. Any insight would be appreciated.

On a related note, since there does seem to have been a lot of changes since `0.1.0`, is there any plans for another release soon?

**Comment by Abrams27** [comment]
Hi, thanks a lot for such detailed explanation!

Lots of things have changed, but we forgot  to update readme (fixed yesterday).

Initialization is quite tricky -- we'll try to simplify it somehow. Also, currently it's still `0.1.0`, but as far as I know we'll try to introduce next verstion soon. Nevertheless, this should help you:

In `bazel-bsp` project reposiotry:
```
./buildAndRunLocally.sh
```

And then in the target repository:
```
coursier launch -r sonatype:snapshots -r central -r file:///~/.m2/repository org.jetbrains.bsp:bazel-bsp:0.1.0 -M org.jetbrains.bsp.bazel.install.Install
```

(all files, incuding `./bsp/.bazelbsp` should be created)

**Comment by ckipp01** [comment]
> And then in the target repository:

So something seems to not be fully publishing correct since if I do those exact steps even on a fresh close of this repository I end up with:

```
~/Documents/java-workspace/bazel-bsp dev
❯ ./buildAndRunLocally.sh
Building server...
============================
INFO: Analyzed target //src/main/java/org/jetbrains/bsp/bazel:bsp-install (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/main/java/org/jetbrains/bsp/bazel:bsp-install up-to-date:
  bazel-bin/src/main/java/org/jetbrains/bsp/bazel/bsp-install.jar
  bazel-bin/src/main/java/org/jetbrains/bsp/bazel/bsp-install
INFO: Elapsed time: 0,130s, Critical Path: 0,00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action


Running server at /Users/ckipp/Documents/java-workspace/bazel-bsp
============================
Bazel BSP server installed in


Done!

~/Documents/java-workspace/bazel-bsp dev
❯ coursier launch -r sonatype:snapshots -r central -r file:///~/.m2/repository org.jetbrains.bsp:bazel-bsp:0.1.0 -M org.jetbrains.bsp.bazel.install.Install

Error: Could not find or load main class org.jetbrains.bsp.bazel.install.Install
Caused by: java.lang.ClassNotFoundException: org.jetbrains.bsp.bazel.install.Install
```

**Comment by Abrams27** [comment]
Sorry for this misunderstanding. Obviously I messed up -- this should help you:

in bsp-bazel repo:
```
bazel build //src/main/java/org/jetbrains/bsp/bazel:bsp-install
export bsp_path="$(bazel info bazel-bin)/src/main/java/org/jetbrains/bsp/bazel/bsp-install"
```

and then in your repo:
```
$bsp_path
```
(it worked for me)

Like I said - it's a bit tricky, tricky enough to trick me.

Sorry for this

**Comment by ckipp01** [comment]
No worries at all, thanks for the explanation. If I'm not mistaken that should be the same as just doing `./buildAndRunLocally.sh <path to repo>`. However your instructions correctly create the bsp dirs, but unfortunately I still have the initial issue of it not being able to connect.

```
2021.06.19 09:11:24 ERROR Timeout waiting for 'build/initialize' response
2021.06.19 09:11:24 ERROR Failed to connect with build server, no functionality will work.
```

Any tips on debugging what my be happening on the bazel-bsp side? If not I'll just start doing a deep dive into trying to figure out what's happening.

**Comment by Abrams27** [comment]
>  If I'm not mistaken that should be the same as just doing ./buildAndRunLocally.sh <path to repo>

yep


I tested it on my own with intellij client and everything succeed. 

What version of bazel are you using? `bazel version`

Maybe your client doesnt create conection correctly or something? does it happen only with bazel-bsp, or maybe other bsp implementations have similiar problems?

**Comment by ckipp01** [comment]
> What version of bazel are you using? `bazel version`

```
❯ bazel version
Build label: 4.1.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

> Maybe your client doesnt create conection correctly or something? does it happen only with bazel-bsp, or maybe other bsp implementations have similiar problems?

So by default [Metals](https://scalameta.org/metals/) uses [Bloop](https://scalacenter.github.io/bloop/), but we've also tested with sbt as a BSP server and also Mill. All of them initialize correctly with Metals. There is a much better chance of me just totally missing something then our BSP discovery and initialization process not working right. It should be pretty battle tested since we fully rely on it working.

I just actually tested with IntelliJ as well, and I actually got a bit more info. When I do try to load the BSP project (this repo) via intelliJ it fails with:

```
java.lang.IllegalArgumentException: Invalid version format

	at org.jetbrains.bsp.bazel.server.bazel.data.SemanticVersion.<init>(SemanticVersion.java:27)

	at org.jetbrains.bsp.bazel.server.bazel.data.SemanticVersion.fromReleaseData(SemanticVersion.java:51)

	at org.jetbrains.bsp.bazel.server.bazel.data.BazelData.<init>(BazelData.java:21)

	at org.jetbrains.bsp.bazel.server.bazel.BazelDataResolver.resolveBazelData(BazelDataResolver.java:30)

	at org.jetbrains.bsp.bazel.server.BazelBspServer.<init>(BazelBspServer.java:48)

	at org.jetbrains.bsp.bazel.server.ServerInitializer.main(ServerInitializer.java:49)
```

Which does give me some places to dig into.

**Comment by Abrams27** [comment]
okey, I believe that our parser is not prepared for the `*-homebrew` version, I'll try to address this issue

**Comment by Abrams27** [comment]
temporary workaround would be changing to version without `homebrew` suffix (`4.*.*` preferable)

second option is to update a source code locally - change `SEMANTIC_VERSION_REGEX` value into `^([0-9]+)\\.([0-9]+)\\.([0-9]+)-homebrew`

**Comment by ckipp01** [comment]
> temporary workaround would be changing to version without `homebrew` suffix (`4.*.*` preferable)
> 
> second option is to update a source code locally - change `SEMANTIC_VERSION_REGEX` value into `^([0-9]+)\\.([0-9]+)\\.([0-9]+)-homebrew`

👍🏼 bingo that did it. I uninstalled with Brew and just did a manual install, and we are back in business. Thanks for helping me track that down! Looking forward to digging more into this.

**Comment by Abrams27** [comment]
Great! Hopefully everything'll be fine now.

If you have any further questions / problems dont hesitate to contact us

**Comment by Abrams27** [comment]
btw, version parser has been updated (you can use homebrew version): https://github.com/JetBrains/bazel-bsp/pull/68
