### ISSUE TITLE
Possibility to grab diagnostic position instead of build target identifier position?

### ISSUE THREAD

**Issue by ckipp01** [JetBrains/bazel-bsp#67]
Wasn't sure how to exactly phrase the issue title, but I noticed given a really small example like:

```scala
package example

object Main extends App {
  val msg: Int = "Let's try to get Bazel BSP working with Metals" // <- line 3

  println(msg)
}
```

I'd sort of expect that the `build/publishDiagnostics` would lead the user to the type mismatch on line 3 so that they are able to quickly make the change and compile again. However, in the given scenario I notice that the diagnostic position that is returned is actually pointing to the `BUILD` file that defines the target.

```
[Trace - 01:43:04 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/metals_bazel_tester/src/example/BUILD"
  },
  "buildTarget": {
    "uri": ""
  },
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 4,
          "character": 13
        },
        "end": {
          "line": 4,
          "character": 13
        }
      },
      "severity": 1,
      "message": "ERROR: /Users/ckipp/Documents/scala-workspace/metals_bazel_tester/src/example/BUILD:4:13: scala //src/example:Example failed: (Exit 1): scalac failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/darwin-fastbuild/bin/src/example/Example.jar-0.params"
    }
  ],
  "reset": false
}
```

This happens both in Metals:

<img width="846" alt="Screenshot 2021-06-21 at 13 47 01" src="https://user-images.githubusercontent.com/13974112/122756821-32da6400-d297-11eb-8e4f-1cf109581585.png">

And also in IntelliJ:

<img width="868" alt="Screenshot 2021-06-21 at 13 47 43" src="https://user-images.githubusercontent.com/13974112/122756895-45ed3400-d297-11eb-9abb-80edf964e843.png">

The actual diagnostic position that a user is probably more interested in is burried in there `build/logMessage`:

```
[Trace - 01:43:05 PM] Received notification 'build/logMessage'
Params: {
  "type": 4,
  "message": "ERROR: /Users/ckipp/Documents/scala-workspace/metals_bazel_tester/src/example/BUILD:4:13: scala //src/example:Example failed: (Exit 1): scalac failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/darwin-fastbuild/bin/src/example/Example.jar-0.params\nsrc/example/Main.scala:4: error: type mismatch;\n found   : String(\"Let\\\u0027s try to get Bazel BSP working with Metals\")\n required: Int\n  val msg: Int \u003d \"Let\u0027s try to get Bazel BSP working with Metals\"\n                 ^\none error found\nBuild failed\njava.lang.RuntimeException: Build failed\n\tat io.bazel.rulesscala.scalac.ScalacWorker.compileScalaSources(ScalacWorker.java:280)\n\tat io.bazel.rulesscala.scalac.ScalacWorker.work(ScalacWorker.java:63)\n\tat io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:92)\n\tat io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:46)\n\tat io.bazel.rulesscala.scalac.ScalacWorker.main(ScalacWorker.java:26)\nTarget //src/example:Example failed to build\nUse --verbose_failures to see the command lines of failed build steps.\nINFO: Elapsed time: 0.220s, Critical Path: 0.09s\nINFO: 2 processes: 2 internal.\nFAILED: Build did NOT complete successfully"
}
```

Again, not super familiar with Bazel yet and still learning how everything is working, but I'm curious if there is a better way to tie into these diagnostics to instead return the diagnostic position in the source file rather than the `BUILD` file. I'd love to hear your thoughts.

**Comment by Abrams27** [comment]
I feel that we might have some bug in our implementation, we'll dig into it.

**Comment by Abrams27** [comment]
hey, I am trying to reproduce it -- unfortunately i cannot. Not even single error diagnostic has been send. Could you send a minimal project with this bug?

btw sorry for such long waiting time
