### ISSUE TITLE
server assumes only scala_test targets - more flexibility needed

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#96]
[ScalaBuildServerService](https://github.com/JetBrains/bazel-bsp/blob/dev/server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/ScalaBuildServerService.java#L41) assumes only `scala_test` targets. Rules Scala has support for scala `junit` tests and `Specs2` support is added via that rule: https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L38 - we need to support it as well

things to do:
- [x] EASY - include such targets in the BSP project
- [ ] HARD - include test classes in the BSP - we need to figure out how to obtain such information from test discovery mechanism

**Comment by Abrams27** [comment]
easy part done in https://github.com/JetBrains/bazel-bsp/pull/101

**Comment by abrams27** [comment]
first point done, second moved: https://youtrack.jetbrains.com/issue/BAZEL-41
